FROM public.ecr.aws/lambda/python:3.10-arm64

RUN pip install onnxruntime==1.13.1 && \
    pip install opencv-python-headless==4.7.0.72 && \
    pip cache purge

COPY ONNX-YOLOv8-Object-Detection ./
COPY onnx-inference-aws-lambda.py app.py

CMD ["app.handler"]