FROM python:3.10-slim AS build

ENV PYTHONUNBUFFERED=1

RUN pip install onnxruntime-gpu==1.15.1 && \
    pip install opencv-python-headless==4.7.0.72 && \
    pip install matplotlib==3.7.1 && \
    pip install torch==2.0.1 && \
    pip install runpod==0.9.11 && \
    pip cache purge

COPY runpod-handler runpod-handler
WORKDIR runpod-handler

CMD ["python", "handler.py"]